// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqducjjatrbmbkjkrosq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZHVjamphdHJibWJramtyb3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTA3MDEsImV4cCI6MjA1NDA4NjcwMX0.ABUi7SOPyA6L8kyDcmHvhpqTx8_QOmpUmeRx6YSCbTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);